### ISSUE TITLE
Works with some

### ISSUE THREAD

**Issue by dev4s** [fsackur/ProfileAsync#4]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/fsackur/ProfileAsync/releases)
- [X] Search the existing issues.

### Steps to reproduce

I'm currently using the previous "version" of the script from your dotfiles repository. This one allowed me to load conda without any problems.  Simple steps - just add the modules/programs in the expected behaviour and you will see :)

### Expected behavior

```console
Should work with:
Import-Module -Name Terminal-Icons
Import-Module -Name PSFzf

"full path removed for clarity"
(& "conda.exe" "shell.powershell" "hook") | Out-String | Where-Object{$_} | Invoke-Expression

Invoke-Expression (& { (zoxide init powershell | Out-String) })
Invoke-Expression (&scoop-search --hook)
```

### Actual behavior

- The starship for ex.: doesn't show actual folder
- conda shows strange error regarding loading the module
- terminal-icons doesn't load
- psfzf totally "blocked" (strange behaviour)
- zoxide doesn't change the folders.

### Environment data

```powershell
Windows 11

Script     0.0                   Conda                               {Enter-CondaEnvironment, Exit-CondaEnvironment, Get-C…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPr…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…
Script     2.6.1                 PSFzf                               {Enable-PsFzfAliases, Invoke-FuzzyEdit, Invoke-FuzzyF…
Script     2.3.6                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remo…
Script     0.11.0                Terminal-Icons                      {Add-TerminalIconsColorTheme, Add-TerminalIconsIconTh…
```

**Comment by fsackur** [comment]
Thanks for the bug report!

I do use starship and don't see issues, so when we get to that point, I'll need more data.

I don't use any of the other apps already, so I'll start by testing with PSFzf.

**Comment by fsackur** [comment]
Notes so far.

When I add `Set-PsFzfOption -PSReadlineChordProvider Ctrl+f` to my profile, and then hit Ctrl-F, I get a brief flash of red text which I've determined says "Object reference not set to an instance of an object."

_bug confirmed_

Set-PsFzfOption passes a scriptblock to PSRL: namely, `{ Invoke-FzfPsReadlineHandlerProvider }`. When the handler is invoked, it goes through the usual mechanism, into internal PS method `internal void InvokeWithPipe` What happens in this case, but not when we run a "straight" profile, is that the handler scriptblock has a different ex context to the default runspace, i.e. `SessionStateInternal.ExecutionContext != context`.

Then the scriptblock is invoked in its own context from `SessionStateInternal.ExecutionContext`, instead of the one from `LocalPipeline.GetExecutionContextFromTLS()`.

https://github.com/PowerShell/PowerShell/blob/ebe0b54/src/System.Management.Automation/engine/lang/scriptblock.cs#L957-L961

The exception is thrown later, at `context.Events.SubscribeEvent` https://github.com/PowerShell/PowerShell/blob/ebe0b54/src/System.Management.Automation/engine/lang/scriptblock.cs#L1008

That's because the `context.Events` is null. In the context from `LocalPipeline.GetExecutionContextFromTLS()`, it is a `PSLocalEventManager`.

All of this makes total sense given that the nature of ProfileAsync is to do things with runspaces that they aren't intended to do.

However, I do want this to work! Continuing to debug.

**Comment by fsackur** [comment]
```powershell
# get "the thing" that does most PSReadLine stuff
$PSRLType = [Microsoft.PowerShell.PSConsoleReadLine]
$PSRL = $PSRLType.GetField("_singleton", "NonPublic, Static").GetValue($PSRLType)

# fish the handler out of PSRL
$dt = $PSRLType.GetField("_dispatchTable", "instance,nonpublic").GetValue($PSRL)
$kvp = $dt.GetEnumerator() | ? {$_.Value.BriefDescription -eq "Fzf Provider Select"}
$FzfHandler = $kvp.Value.ScriptBlock

# Fails
# & $FzfHandler

# Dig into the handler scriptblock
$SSIProp = [scriptblock].GetProperty("SessionStateInternal", [System.Reflection.BindingFlags]"Instance,NonPublic")
$SSI = $SSIProp.GetValue($FzfHandler)
$ExCtxProp = $SSI.GetType().GetProperty("ExecutionContext", [System.Reflection.BindingFlags]"Instance,NonPublic")
$SBContext = $ExCtxProp.GetValue($SSI)  # the handler's ExCtx
$EventsProp = $SBContext.GetType().GetProperty("Events", [System.Reflection.BindingFlags]"Instance,NonPublic")

<#
    # Get the event mgr from the default rs
    $RsCtxProp = [runspace]::DefaultRunspace.GetType().GetProperty("ExecutionContext", [System.Reflection.BindingFlags]"Instance,NonPublic")
    $LocalContext = $RsCtxProp.GetValue([runspace]::DefaultRunspace)
    $RsEventMgr = $EventsProp.GetValue($LocalContext)

    # Shove it into the handler
    $EventsProp.SetValue($Context, $RsEventMgr)

    # Now do Ctrl-F
    # Works
    # But... when you finish with FZF, the shell is locked up hard. Presumably a deadlock.
#>

$EvMgr = [pscustomobject].Assembly.CreateInstance(
    "System.Management.Automation.PSLocalEventManager", $true, 
    "Instance,NonPublic", $null, @($SBContext), $null, @())

$EventsProp.SetValue($SBContext, $EvMgr)

# Now do Ctrl-F
# System.Management.Automation.PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:  Invoke-FzfPsReadlineHandlerProvider 
#    at System.Management.Automation.ScriptBlock.GetContextFromTLS()
#    at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
#    at System.Management.Automation.ScriptBlock.OnScriptBlockInvokeEventHandler(Object sender, PSEventArgs args)
# --- End of stack trace from previous location ---
#    at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
#    at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
#    at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass260_0.<SetKeyHandler>g__HandlerWrapper|0(Nullable`1 k, Object arg) in /home/freddie/gitroot/upstream/PSReadLine/PSReadLine/Options.cs:line 272
```

💡💡💡

...Maybe I shouldn't dispose of the runspace...

**Comment by fsackur** [comment]
Hi @dev4s , I've got PSFzf working on my box. Could you try v0.2.0 and see if this fixes the other issues?

`Install-Module ProfileAsync`

**Comment by fsackur** [comment]
Hi @dev4s , AFAICS this is fixed. Feel free to re-open if needed.

**Comment by dev4s** [comment]
Hi @fsackur, thanks for a good job, I will test it when I need it, the situation has changed :) But still - outstanding job! :)

**Comment by brian6932** [comment]
For some reason when I use:
```pwsh
Import-ProfileAsync {
	Import-Module PSFzf
	Set-PsFzfOption -TabExpansion -PSReadlineChordProvider Ctrl+t -PSReadlineChordReverseHistory Ctrl+r
}
```
Pressing <kbd>CTRL</kbd>+<kbd>R</kbd>-><kbd>ESC</kbd> freezes my prompt, but when it's not within the `Import-ProfileAsync` block, it works.

Also when it's outside of the `Import-ProfileAsync` block, `Import-Module PSFzf` isn't required. Related to and mentioned in #16.
